### ISSUE TITLE
Use Article images from PlaceCal

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#265] opened 2022-05-04 17:29 UTC
## User story
Noted in #85 - Georgie has added images for News

## Acceptance criteria
- [ ] If an article has image uploaded in PlaceCal, that image is displayed in TransDimension

**Comment by kimadactyl** [comment] 2022-09-12 14:18
This is a dupe of  #137

**Closed by kimadactyl** 2022-09-12 14:18 UTC
Labels: ee, v
